### ISSUE TITLE
Broken example gifs in README.md

### ISSUE THREAD

**Issue by Ryuno-Ki** [dthigpen/todotxt-extension#1]
**Describe the bug**
Currently, the examples don't show up in the README.md

**To Reproduce**
1. Go to [README.md](https://github.com/dthigpen/todotxt-extension/blob/e54444973e555ca8fb82e8d35acfeeaa62284569/README.md)
3. Scroll down to [examples](https://github.com/dthigpen/todotxt-extension/blob/e54444973e555ca8fb82e8d35acfeeaa62284569/README.md#examples)
4. See ExampleUsage ExampleUsage

**Expected behavior**
The GIFs for [video1](https://github.com/dthigpen/todotxt-extension/blob/master/examples/vid1.gif) and [video2](https://github.com/dthigpen/todotxt-extension/blob/master/examples/vid2.gif)

**Additional context**
I assume, you've added them via a feature branch and need to replace the „example” with „master” in the path :-)

**Comment by dthigpen** [comment]
Thanks, spot on!
Should be fixed in commit 6ed0929663e8529accd607a0d933292e644e250a
